/************************************************************************
* Programmer:  Ruben Ramirez
*
* Course:  CSCI 1320.01
*
* Date: March 3, 2016 
*
* Assignment Number | Keyword : 11 | search
*
* Point Value :  100
*
* Environment:  visual studio 2013
*
* Files Included:  none
*
* Purpose:  To write iterator (“for” loop) statements.  
* To use the C standard library and call the srand and rand functions.  
* This program is to search for a number given by the user in a list of numbers generated by the instructor.  
* To use the array type.
*
* Input: none
*
* Preconditions: none
*
* Output:  a list of 30 random numbers and a print statement if a user input matches one of those numbers
*
* Postconditions: none
*
* Algorithm: for loop and if statement
*
*
* Errors: if the user inputs a floating point number the input
*  is truncated. In the future: add code to handle the floats
*  if the user inputs a non-number, the program will exit
*
* Example: Show an example in terms of input and output (if appropriate)
*
* History: Useful if assignments are based on the same project
*  indention - please do not use tabs - 2 or 3 spaces
***********************************************************************/

#include <stdio.h> 
#include <stdlib.h>  // to call rand funcions
#include <stdbool.h>

#define equals ==


/* function prototypes (function declarations go above main) */

int main(void)
{
	// declare an array of integers
	int numbers[30];
	int index;
	int num2Find;

	// identify the author of the program in the output
	printf("nn_program_keyword_student_name");


	//*** Do not modify this code *** !!

	srand(747);

	// fill the array with random numbers
	for (index = 0; index < 30; index++)
	{
		numbers[index] = rand();
	}


	printf("\n\nI have a list of numbers, try to guess one number in that list!\n");
	printf("If you enter an INTEGER number to find, then press the Enter key. I will search my list :\n");
	scanf("%i", &num2Find);

	// Show the user what they entered
	printf("\nJust to be clear, You entered: %i\n\n", num2Find);

	//*** end of code the student should NOT modify *** !!!

	

	// declarations
	bool found;
	found = true;
	int count;
	count = 0;

	// Student writes code here to print the list.  
	printf("\nPosition\tCurrent Number\n");

	for (int index = 0; index < 30; index++)  // list of random numbers

	{

		printf("%i\t\t%i\t\t\n", index+1, numbers[index]);

	}


	for (int index = 0; index < 30; index++)

	{



		// Student code goes here to try to find the number entered in the list of numbers

		if (num2Find equals numbers[index])

		{
			// Student writes code to print if the number is found.
			// If the number is found the student should also print the location of the number in the list.
			printf("\nYour number %i was found at position %i in the list.\n", num2Find, index+1);
					
		
		}
		
				
		else
		{
			
			found = false;
			count = count++;

		}


	}
	
	if (found equals false && count equals 30)
	{
		printf("\nYour number %i was not found in a list of %i numbers.\n", num2Find, count);
	}
	else
	{


	}
	
	return 0;
}   // end of main




